### ISSUE TITLE
Add a page that redirects from bpo to GitHub

### ISSUE THREAD

**Issue by ezio-melotti** [psf/gh-migration#17]
As a follow-up of #15, once we have the GitHub id as an attribute in the issue items, we need to create a new script accessible through a URL like `bugs.python.org/redirect/BPO-ID` that redirects to the corresponding GitHub issue.  This could be deployed and tested with fake IDs even before the migration starts.

The plan is to replace `#XXXXX` issues references with `BPO-XXXXX` in messages and set GitHub autolinking to point to `bugs.python.org/redirect/XXXXX`, which in turn redirects back to the corresponding GitHub issue.

**Comment by ezio-melotti** [comment]
This is now live on b.p.o, even though none of the bpo issues (except `#2771`) have a linked GitHub issue.

To use the redirect, open `https://bugs.python.org/issue?@action=redirect&bpo=BPOID`, and if the bpo issue exists and has a linked GitHub issue, it will automatically redirect to it.  This can be combined with autolinking on the `bpo-` prefix to link to the redirect page, e.g. bpo-2771.

**Comment by arhadthedev** [comment]
Since each closed gh-migration issue is not just an informational project board entry but is backed by some PR, I believe they should link to corresponding PRs for historical context.

**Comment by arhadthedev** [comment]
https://github.com/psf/bpo-tracker-cpython/pull/13
